name: venus
channels:
  - ostrokach
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - bioconda
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - anarci=2024.05.21=pyhdfd78af_0
  - aria2=1.37.0=hbc8128a_2
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.1.31=hbcca054_0
  - conda-pack=0.8.1=pyhd8ed1ab_1
  - dssp=2.2.1=1
  - foldseek=9.427df8a=pl5321h5021889_2
  - gawk=5.3.1=hcd3d067_0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - gmp=6.3.0=hac33072_2
  - hmmer=3.4=h503566f_3
  - intel-openmp=2021.4.0=h06a4308_3561
  - ld_impl_linux-64=2.40=h12ee557_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - liblzma=5.6.3=hb9d3cd8_1
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.47.2=hee588c1_0
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.5=h0d44e9d_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=19.1.6=h024ca30_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - mmseqs2=16.747c6=pl5321hd6d6fdc_1
  - mpfr=4.2.1=h90cbb55_3
  - ncurses=6.5=he02047a_1
  - openssl=3.4.1=h7b32b05_0
  - perl=5.32.1=7_hd590300_perl5
  - pip=24.2=py310h06a4308_0
  - python=3.10.16=he725a3c_1_cpython
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - tk=8.6.13=noxft_h4845f30_101
  - tmux=3.3a=h5eee18b_1
  - wget=1.21.4=hda4d442_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.3.1=hb9d3cd8_2
  - pip:
      - accelerate==1.1.1
      - accelerator==2024.9.13
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.11.7
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==5.0.1
      - attrs==24.2.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bio==1.7.1
      - biopython==1.84
      - biothings-client==0.3.1
      - biotite==0.41.2
      - biotraj==1.2.2
      - bleach==6.2.0
      - bottle==0.12.25
      - brotli==1.1.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - cftime==1.6.4.post1
      - charset-normalizer==3.4.0
      - click==8.1.7
      - cloudpathlib==0.20.0
      - comm==0.2.2
      - contourpy==1.3.1
      - cycler==0.12.1
      - datasets==3.1.0
      - debugpy==1.8.9
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - easydict==1.13
      - einops==0.8.0
      - esm==3.1.3
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - faiss-cpu==1.9.0.post1
      - fake-useragent==1.5.1
      - fastapi==0.115.5
      - fastjsonschema==2.21.1
      - ffmpy==0.4.0
      - filelock==3.13.1
      - fonttools==4.55.0
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gprofiler-official==1.0.0
      - gradio==5.6.0
      - gradio-client==1.4.3
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.26.2
      - icetk==0.0.7
      - idna==3.10
      - ipykernel==6.29.5
      - ipython==8.29.0
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.3
      - joblib==1.4.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.2
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - kiwisolver==1.4.7
      - latex2mathml==3.77.0
      - lightning-utilities==0.11.9
      - llvmlite==0.43.0
      - lmdb==1.5.1
      - lxml==5.3.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mdtex2html==1.3.0
      - mdtraj==1.10.2
      - mdurl==0.1.2
      - mistune==3.0.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgpack-numpy==0.4.8
      - multidict==6.1.0
      - multiprocess==0.70.16
      - mygene==3.2.2
      - narwhals==1.31.0
      - nbclient==0.10.1
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - netcdf4==1.7.2
      - networkx==3.2.1
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu12==12.1.105
      - openpyxl==3.1.5
      - orjson==3.10.11
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - peft==0.14.0
      - pexpect==4.9.0
      - pillow==10.2.0
      - platformdirs==4.3.6
      - plotly==6.0.1
      - pooch==1.8.2
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.48
      - propcache==0.2.0
      - protobuf==5.29.3
      - psutil==6.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==18.0.0
      - pycparser==2.22
      - pydantic==2.10.1
      - pydantic-core==2.27.1
      - pydub==0.25.1
      - pyg-lib==0.4.0+pt25cu121
      - pygments==2.18.0
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - python-multipart==0.0.12
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - rdkit==2024.3.6
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rpds-py==0.22.3
      - ruff==0.8.0
      - safehttpx==0.1.1
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - sentry-sdk==2.19.0
      - setproctitle==1.3.4
      - shellingham==1.5.4
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - starlette==0.41.3
      - sympy==1.13.1
      - tenacity==9.0.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.4.0
      - tokenizers==0.20.3
      - tomli==2.2.1
      - tomlkit==0.12.0
      - torch==2.5.1+cu121
      - torch-cluster==1.6.3+pt25cu121
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt25cu121
      - torch-sparse==0.6.18+pt25cu121
      - torch-spline-conv==1.2.2+pt25cu121
      - torchaudio==2.5.1+cu121
      - torchmetrics==1.6.1
      - torchtext==0.18.0
      - torchvision==0.20.1+cu121
      - tornado==6.4.2
      - tqdm==4.67.0
      - traitlets==5.14.3
      - transformers==4.46.3
      - triton==3.1.0
      - typer==0.13.1
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - uri-template==1.3.0
      - urllib3==2.2.3
      - uvicorn==0.32.1
      - waitress==3.0.2
      - wandb==0.19.4
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==12.0
      - xxhash==3.5.0
      - yarl==1.18.0
      - zstd==1.5.6.1
prefix: /home/tanyang/miniconda3/envs/protrem
